version: '2'

services:
  telegram_api:
    image: telegram_api:v.1.0
    container_name: telegram_api
    build:
      context: ./../ 
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    mem_limit: 64m
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "8008:8008"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"      
    environment: 
      - ENV=${ENV}

